/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsnRouteImport } from './routes/ssn'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckRouteImport } from './routes/check'
import { Route as IndexRouteImport } from './routes/index'

const SsnRoute = SsnRouteImport.update({
  id: '/ssn',
  path: '/ssn',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckRoute = CheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check': typeof CheckRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/ssn': typeof SsnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check': typeof CheckRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/ssn': typeof SsnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check': typeof CheckRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/ssn': typeof SsnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/check' | '/dashboard' | '/profile' | '/ssn'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/check' | '/dashboard' | '/profile' | '/ssn'
  id: '__root__' | '/' | '/check' | '/dashboard' | '/profile' | '/ssn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckRoute: typeof CheckRoute
  DashboardRoute: typeof DashboardRoute
  ProfileRoute: typeof ProfileRoute
  SsnRoute: typeof SsnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ssn': {
      id: '/ssn'
      path: '/ssn'
      fullPath: '/ssn'
      preLoaderRoute: typeof SsnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check': {
      id: '/check'
      path: '/check'
      fullPath: '/check'
      preLoaderRoute: typeof CheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckRoute: CheckRoute,
  DashboardRoute: DashboardRoute,
  ProfileRoute: ProfileRoute,
  SsnRoute: SsnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
